util.AddNetworkString("izc_addEntity")
util.AddNetworkString("izc_removeEntity")
util.AddNetworkString("izc_addMaterialForEntity")
util.AddNetworkString("izc_removeMaterialForEntity")
util.AddNetworkString("izc_updateMaterialPropsForEntity")
util.AddNetworkString("izc_requestEntities")
